<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCustomerOrderTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customer_order', function (Blueprint $table) {
            $table->integer('id');
            $table->string('uuid');
            $table->integer('customer_id');
            $table->timestamp('order_time')->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->string('delivery_address', 255)->nullable();
            $table->string('delivery_email_address', 255);
            $table->timestamp('preferred_delivery_time')->nullable();
            $table->timestamp('time_paid')->nullable();
            $table->timestamp('time_sent')->nullable();
            $table->decimal('total_price', 10, 2);
            $table->decimal('discount', 10, 2);
            $table->decimal('final_price', 10, 2);
            $table->nullableTimestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customer_order');
    }
}
