<?php

namespace App\Http\Controllers;

use App\CustomerOrder;
use App\Ticket;
use App\TicketCategory;
use Inertia\Inertia;
use Razorpay\Api\Api;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Razorpay\Api\Errors\SignatureVerificationError;

class CheckoutController extends Controller
{
    public function create()
    {
        $razorKey = config('razorpay.razor_key');
        $razorSecret = config('razorpay.razor_secret');
        $api = new Api($razorKey, $razorSecret);
        $cartTotal = floatval(preg_replace("/[^-0-9\.]/", "", Cart::total()));

        if (Cart::count() > 0 && $cartTotal >= 1) {
            $nowTime = (string) Carbon::now();
            $receiptId = Str::random(32);
            // initialise order for customer
            $order = CustomerOrder::create([
                'user_id' => 1,
                'receipt_id' => $receiptId, // receipt id generated by systme for creating order in razorpay  
                'order_time' => $nowTime,
            ]);

            $orderData = [
                'receipt'         => $receiptId,
                'amount'          => $cartTotal * 100, // total amount in paise
                'currency'        => 'INR',
                'payment_capture' => 1 // auto capture
            ];

            $razorpayOrder = $api->order->create($orderData);

            $razorpayOrderId = $razorpayOrder['id'];

            $orderTime = Carbon::createFromTimestamp($razorpayOrder['created_at'])->toDateTimeString();

            // save the customer order with order id and order time
            $order->razorpay_order_id = $razorpayOrderId;
            $order->order_time = $orderTime;
            $order->save();

            session()->put('razorpay_order_id', $razorpayOrderId);

            $amount = $orderData['amount'];

            $data = [
                "key"               => $razorKey,
                "amount"            => $amount,
                "name"              => "DJ Tiesto",
                "description"       => "Tron Legacy",
                "image"             => "https://s29.postimg.org/r6dj1g85z/daft_punk.jpg",
                "prefill"           => [
                    "name"              => "Daft Punk",
                    "email"             => "customer@merchant.com",
                    "contact"           => "9999999999",
                ],
                "notes"             => [
                    "address"           => "Hello World",
                    "merchant_order_id" => "12312321",
                ],
                "theme"             => [
                    "color"             => "#F37254"
                ],
                "order_id"          => $razorpayOrderId,
            ];
            $data['display_currency']  = 'INR';
            $data['display_amount']    = $amount / 100;

            return Inertia::render('Front/BuyTickets/Checkout', [
                'cart' => Cart::content()->values(),
                'total' => $cartTotal,
                'options' => $data
            ]);
        } else {
            return Inertia::render('Front/BuyTickets/EmptyCart');
        }
    }

    public function verifyPayment(Request $request)
    {
        // dd($request->all());
        $razorKey = config('razorpay.razor_key');
        $razorSecret = config('razorpay.razor_secret');
        $api = new Api($razorKey, $razorSecret);
        $cartTotal = floatval(preg_replace("/[^-0-9\.]/", "", Cart::total()));
        $cartDiscount = floatval(preg_replace("/[^-0-9\.]/", "", Cart::discount()));
        $cartSubtotal = floatval(preg_replace("/[^-0-9\.]/", "", Cart::subtotal()));

        $success = true;
        $error = "Payment Failed";

        if ($request->has('razorpay_payment_id')) {
            try {
                // Please note that the razorpay order ID must
                // come from a trusted source (session here, but
                // could be database or something else)
                $attributes = array(
                    'razorpay_order_id' => session()->get('razorpay_order_id'),
                    'razorpay_payment_id' => $request->razorpay_payment_id,
                    'razorpay_signature' => $request->razorpay_signature
                );

                $api->utility->verifyPaymentSignature($attributes);
            } catch (SignatureVerificationError $e) {
                $success = false;
                $error = 'Razorpay Error : ' . $e->getMessage();
            }
        }

        // DB::transaction(function () use ($request, $cartTotal, $cartDiscount, $cartSubtotal) {
        //start ticket creation
        $ticketCategories = Cart::content()->values();

        $nowTime = (string) Carbon::now();

        $order = CustomerOrder::updateOrCreate([
            'user_id' => 1,
            'razorpay_order_id' => session()->get('razorpay_order_id'),
        ], [
            'razorpay_payment_id' => $request->razorpay_payment_id,
            'total_price' => $cartTotal,
            'discount' => $cartDiscount,
            'final_price' => $cartSubtotal
        ]);
        // dd($ticketCategories);
        $ticketCategories->each(function ($category) use ($nowTime, $order) {
            $categoryFound = TicketCategory::where('uuid', $category->id)->first();
            // dd($category, $categoryFound);
            if ($categoryFound) {
                $ticket = Ticket::create([
                    'serial_number' => Str::upper(Str::random(8)),
                    'event_id' => $categoryFound->event_id,
                    'ticket_category_id' => $categoryFound->id,
                    'purchase_date' => $nowTime
                ]);
                // dd($ticket);
                $order->ordertickets()->create([
                    'ticket_id' => $ticket->id
                ]);

                $categoryFound->no_of_tickets_left = $categoryFound->no_of_tickets_left--;
                $categoryFound->save();
            }
        });
        Cart::destroy();
        session()->forget('razorpay_order_id');
        // });

        if ($success === true) {
            $html = "<p>Your payment was successful</p>
             <p>Payment ID: {$request->razorpay_payment_id}</p>";
            session()->flash('success', $html);
        } else {
            $html = "<p>Your payment failed</p>
                <p>{$error}</p>";
            session()->flash('error', $html);
        }
        return redirect('/checkout');
    }
}
